### ISSUE TITLE
Can not push to origin.

### ISSUE THREAD

**Issue by pjmanley671** [gadsu/Murder#1]
This is just a note that I do not have sufficient access to submit the current files of the game.

**Comment by skudge** [comment]
?Hi, Paul --


I've tried changing some permissions. Let me know whether it works now. (Or at least whether you have the permissions to change settings and etc.). In theory you have admin privileges for the Murder repository


cheers,

skg


steve graham

associate professor

computer game design

dakota state university

skg@dsu.edu

605-480-6603

________________________________
